# Generated by Django 3.0.5 on 2020-04-13 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0004_auto_20200413_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criaçao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
