# Generated by Django 3.0.5 on 2020-04-13 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0005_auto_20200413_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criaçao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
