# Generated by Django 3.0.5 on 2020-04-13 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0007_auto_20200413_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criaçao',
            field=models.TextField(blank=True, default=django.utils.timezone.now, max_length=30),
        ),
    ]
